# Generated by Django 5.2 on 2025-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Телеграм чат-id"),
        ),
    ]